FREE_HOSTING = [
    "netlify.app",
    "github.io",
    "vercel.app",
    "glitch.me",
    "replit.dev",
    "weebly.com",
    "wix.com",
    "blogspot.com",
    "wordpress.com",
    "sites.google.com",
    "000webhostapp.com",
    "infinityfreeapp.com",
    "bsite.net",
    "freehostia.com",
    "x10host.com",
    "byethost",
    "freehosting",
    "hostfree",
]

RISKY_TLDS = {"tk", "ml", "ga", "cf", "gq", "buzz", "xyz", "top", "click", "link", "work", "date"}

URL_SHORTENERS = {
    "bit.ly",
    "tinyurl.com",
    "t.co",
    "goo.gl",
    "ow.ly",
    "is.gd",
    "buff.ly",
    "adf.ly",
    "shorte.st",
    "bc.vc",
    "clk.sh",
    "rb.gy",
    "cutt.ly",
    "shorturl.at",
    "tiny.cc",
}

TRUSTED_DOMAINS = {
    "google.com",
    "youtube.com",
    "facebook.com",
    "instagram.com",
    "twitter.com",
    "x.com",
    "linkedin.com",
    "microsoft.com",
    "apple.com",
    "amazon.com",
    "netflix.com",
    "wikipedia.org",
    "github.com",
    "stackoverflow.com",
    "reddit.com",
    "paypal.com",
    "orange.com",
    "mtn.com",
    "orange.ci",
    "wave.com",
    "moov.ci",
    "gouv.ci",
    "impots.ci",
    "tresor.ci",
    "bceao.int",
}

SUSPICIOUS_KEYWORDS_URL = [
    ("urgent", 15),
    ("urgence", 15),
    ("paiement", 12),
    ("payment", 12),
    ("recrute", 12),
    ("recrutement", 12),
    ("frais", 15),
    ("promo", 8),
    ("gagner", 12),
    ("winner", 10),
    ("gratuit", 8),
    ("cadeau", 10),
    ("gift", 10),
    ("verify", 12),
    ("verif", 12),
    ("confirm", 10),
    ("login", 8),
    ("password", 10),
    ("bank", 12),
    ("banque", 12),
    ("paypal", 15),
    ("amazon", 12),
    ("mtn", 8),
    ("moov", 8),
    ("wave", 6),
    ("orange", 6),
]

SUSPICIOUS_CONTENT_KEYWORDS = [
    "mot de passe",
    "password",
    "identifiant",
    "numero de telephone",
    "numéro de téléphone",
    "frais d'inscription",
    "frais de dossier",
    "virement",
    "western union",
    "moneygram",
    "paiement immediat",
    "paiement immédiat",
    "offre limitee",
    "offre limitée",
    "ne ratez pas",
    "felicitations",
    "félicitations",
    "vous avez gagne",
    "vous avez gagné",
    "cliquez maintenant",
    "remplissez le formulaire",
    "envoyez vos informations",
    "compte bancaire",
    "carte de credit",
    "carte de crédit",
    "cvv",
    "code secret",
    "recrutement urgent",
    "emploi immediat",
    "emploi immédiat",
    "sans experience",
    "sans expérience",
    "travail a domicile",
    "travail à domicile",
    "gain facile",
]

AFRICA_BLACKLIST = [
    "mtn-ci-promo",
    "orange-money-ci",
    "wave-transfert",
    "recrutement-ci",
    "emploi-abidjan",
    "bourse-etude-ci",
    "visa-ci",
    "concours-mtn",
    "concours-orange",
    "tresor-ci",
    "douane-ci",
    "cnps-ci",
    "cie-ci",
    "sodeci",
    "moov-money",
    "airtel-money",
    "momo-gratuit",
    "ivoirjob",
    "ci-emploi",
    "emploi-dakar",
    "emploi-mali",
    "recrutement-senegal",
]

BRAND_TYPOSQUAT = {
    "paypal": ["paypa1", "pay-pal", "paypai", "paypall", "paypal-ci", "paypal-secure"],
    "orange": ["0range", "orang3", "orange-ci-money", "orangemoney-ci", "orange-money"],
    "mtn": ["mtn-ci", "mtn-money", "mtnci", "m-t-n", "mtn2", "mtnpromo"],
    "wave": ["waave", "wave-ci", "wave-money", "wavemoney", "wave-transfert"],
    "amazon": ["amaz0n", "amazzon", "amazon-promo", "amazon-ci", "amazonn"],
    "google": ["g00gle", "gooogle", "googIe", "google-ci", "googlesecure"],
    "microsoft": ["micros0ft", "microsooft", "microsoft-secure", "micr0soft"],
    "apple": ["appIe", "app1e", "apple-id-secure", "apple-verify"],
    "facebook": ["faceb00k", "facebok", "facebook-ci", "face-book"],
    "instagram": ["instagr4m", "instagran", "instagram-ci", "insta-gram"],
    "whatsapp": ["whatsap", "whatsapp-ci", "whatssapp", "whatsapp-promo"],
    "linkedin": ["linkedln", "linke-din", "linkedin-job"],
    "moov": ["m00v", "moov-ci", "moov-money", "moovcash"],
}

KNOWN_BRANDS = ["paypal", "orange", "mtn", "wave", "amazon", "apple", "microsoft", "facebook", "google"]
